name: logger_beauty
description: A Flutter package help your debug screen more beautiful.
version: 1.0.1
homepage: https://github.com/hiimBugCreator/logger_beauty/

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3